project:
  type: website
  output-dir: docs

website:
  title: "GSWEP4R Tutorial"
  description: "useR! Tutorial: Good Software Engineering Practice with R"
  favicon: favicon.ico
  site-url: https://RCONIS.github.io/user2024-tutorial-gswep
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: "house-fill"
      - href: listing.qmd
        text: Slides
        icon: "file-earmark-slides"
  page-footer:
    center:
      - text: "About"
        href: https://rconis.com/about/
      - text: "Imprint"
        href: https://rconis.com/imprint/
      - text: "Contact"
        href: https://rconis.com/contact/

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true

editor: source
